package companymanagementsystem.page;

import companymanagementsystem.entity.Employee;
import companymanagementsystem.connections.EmployeeDatabaseOperations;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXCALIBUR
 */
public class EmployeePage extends javax.swing.JFrame {

    private final DefaultTableModel tableModel;

    public EmployeePage() {
        initComponents();
        setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) employeeTable.getModel();
        displayEmployees();
    }

    private void displayEmployees() {
        EmployeeDatabaseOperations employeeDatabaseOperations = new EmployeeDatabaseOperations();
        List<Employee> employees = employeeDatabaseOperations.getAllEmployees();

        for (Employee emp : employees) {
            Object[] rowData = {
                emp.getId(),
                emp.getFirstname(),
                emp.getSurname(),
                emp.getPosition()
            };
            tableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        employeeAnnouncmentMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        employeeIdLabel = new javax.swing.JLabel();
        employeeFirstnameLabel = new javax.swing.JLabel();
        employeeSurnameLabel = new javax.swing.JLabel();
        employeePositionLabel = new javax.swing.JLabel();
        employeeIdArea = new javax.swing.JTextField();
        employeeFirstnameArea = new javax.swing.JTextField();
        employeeSurnameArea = new javax.swing.JTextField();
        employeePositionArea = new javax.swing.JTextField();
        employeeInsertButton = new javax.swing.JButton();
        employeeUpdateButton = new javax.swing.JButton();
        employeeDeleteButton = new javax.swing.JButton();
        employeeToProductButton = new javax.swing.JButton();
        employeeSignOut = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 0));

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "employee_id", "firstname", "surname", "position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(employeeTable);

        employeeAnnouncmentMessage.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        employeeAnnouncmentMessage.setForeground(new java.awt.Color(0, 102, 0));
        employeeAnnouncmentMessage.setText("Announcement");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(employeeAnnouncmentMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(employeeAnnouncmentMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("</ EMPLOYEE PAGE >");

        employeeIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeIdLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeeIdLabel.setText("employee_id :");

        employeeFirstnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeFirstnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeeFirstnameLabel.setText("firstname :");

        employeeSurnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeSurnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeeSurnameLabel.setText("surname :");

        employeePositionLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeePositionLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeePositionLabel.setText("position :");

        employeePositionArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeePositionAreaActionPerformed(evt);
            }
        });

        employeeInsertButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeInsertButton.setForeground(new java.awt.Color(51, 153, 0));
        employeeInsertButton.setText("INSERT");
        employeeInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeInsertButtonActionPerformed(evt);
            }
        });

        employeeUpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeUpdateButton.setForeground(new java.awt.Color(51, 153, 0));
        employeeUpdateButton.setText("UPDATE");
        employeeUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeUpdateButtonActionPerformed(evt);
            }
        });

        employeeDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeDeleteButton.setForeground(new java.awt.Color(51, 153, 0));
        employeeDeleteButton.setText("DELETE");
        employeeDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeDeleteButtonActionPerformed(evt);
            }
        });

        employeeToProductButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeToProductButton.setForeground(new java.awt.Color(51, 153, 0));
        employeeToProductButton.setText("PRODUCTS");
        employeeToProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeToProductButtonActionPerformed(evt);
            }
        });

        employeeSignOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeSignOut.setForeground(new java.awt.Color(51, 153, 0));
        employeeSignOut.setText("SIGN OUT");
        employeeSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(employeeToProductButton)
                .addGap(18, 18, 18)
                .addComponent(employeeSignOut)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(employeeFirstnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(employeeIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(employeePositionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(employeePositionArea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeeDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeFirstnameArea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeIdArea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeSurnameArea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeUpdateButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeInsertButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeToProductButton)
                    .addComponent(jLabel1)
                    .addComponent(employeeSignOut))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeIdLabel)
                    .addComponent(employeeIdArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeInsertButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeFirstnameLabel)
                            .addComponent(employeeFirstnameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeSurnameLabel)
                            .addComponent(employeeSurnameArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(employeeUpdateButton)
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeePositionLabel)
                    .addComponent(employeePositionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeDeleteButton))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeePositionAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePositionAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePositionAreaActionPerformed

    private void employeeDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDeleteButtonActionPerformed
        employeeAnnouncmentMessage.setText("");
        int selectedRowIndex = employeeTable.getSelectedRow();

        Object primaryKeyValue = employeeTable.getValueAt(selectedRowIndex, 0);
        String primaryKeyValueAsString = primaryKeyValue.toString();
        if (selectedRowIndex == -1) {
            if (employeeTable.getRowCount() == 0) {
                employeeAnnouncmentMessage.setText("Table is Empty...");
                return;
            }

            employeeAnnouncmentMessage.setText("Please click on a row to Delete Employee");
            return;
        }
        EmployeeDatabaseOperations employeeDatabaseOperations = new EmployeeDatabaseOperations();

        if (employeeDatabaseOperations.deleteEmployee(primaryKeyValueAsString)) {
            tableModel.setRowCount(0);
            displayEmployees();
            employeeAnnouncmentMessage.setText("Employee Successfully Deleted...");
            return;
        }
        employeeAnnouncmentMessage.setText("Employee Delete Attempt Failed...");
        return; // if 'in else i yerine geçen return


    }//GEN-LAST:event_employeeDeleteButtonActionPerformed

    private void employeeInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeInsertButtonActionPerformed
        String employeeId = employeeIdArea.getText();
        String firstname = employeeFirstnameArea.getText();
        String surname = employeeSurnameArea.getText();
        String position = employeePositionArea.getText();

        /*if (!isEmployeeNumeric(employeeId)) {
            employeeAnnouncmentMessage.setText("employee_id should be a valid positive integer.");
            return;
        }

        if (!isEmployeeNumeric(firstname)) {
            employeeAnnouncmentMessage.setText("firstname should be a valid string.");
            return;
        }

        if (!isEmployeeValidString(surname)) {
            employeeAnnouncmentMessage.setText("surname should be a valid string.");
            return;
        }

        if (!isEmployeeValidString(position)) {
            employeeAnnouncmentMessage.setText("position should be a valid string.");
            return;
        } */

        if (employeeId.isEmpty() || firstname.isEmpty() || surname.isEmpty() || position.isEmpty()) {

            employeeAnnouncmentMessage.setText("Please Fill All the Fields to Insert Employee Successfully...");
            return;
        }
        Employee newEmployee = new Employee();
        
        newEmployee.setId(Long.valueOf(employeeId));
        newEmployee.setFirstname(firstname);
        newEmployee.setSurname(surname);
        newEmployee.setPosition(position);
        
        EmployeeDatabaseOperations employeeDatabaseOperations = new EmployeeDatabaseOperations();
        boolean success = employeeDatabaseOperations.insertEmployee(newEmployee);

        if (success) {
            tableModel.setRowCount(0);
            displayEmployees();
            employeeIdArea.setText("");
            employeeFirstnameArea.setText("");
            employeeSurnameArea.setText("");
            employeePositionArea.setText("");

            employeeAnnouncmentMessage.setText("Employee Inserted Succesfully...");
        } else {
            employeeAnnouncmentMessage.setText("Failed to Insert Employee, Try Again...");
        }


    }//GEN-LAST:event_employeeInsertButtonActionPerformed

    private void employeeToProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeToProductButtonActionPerformed
        setVisible(false);
        ProductPage productPage = new ProductPage();
        productPage.setVisible(true);
    }//GEN-LAST:event_employeeToProductButtonActionPerformed

    private void employeeSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSignOutActionPerformed
        setVisible(false);
        HomePage homepage = new HomePage();
        homepage.setVisible(true);
    }//GEN-LAST:event_employeeSignOutActionPerformed

    private void employeeUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeUpdateButtonActionPerformed
        String employeeId = employeeIdArea.getText();
        String firstname = employeeFirstnameArea.getText();
        String surname = employeeSurnameArea.getText();
        String position = employeePositionArea.getText();

        if (!isEmployeeNumeric(employeeId)) {
            employeeAnnouncmentMessage.setText("employee_id should be a valid positive integer.");
            return;
        }

        if (!isEmployeeNumeric(firstname)) {
            employeeAnnouncmentMessage.setText("firstname should be a valid string.");
            return;
        }

        if (!isEmployeeValidString(surname)) {
            employeeAnnouncmentMessage.setText("surname should be a valid string.");
            return;
        }

        if (!isEmployeeValidString(position)) {
            employeeAnnouncmentMessage.setText("position should be a valid string.");
            return;
        }
        if (employeeId.isEmpty() || firstname.isEmpty() || surname.isEmpty() || position.isEmpty()) {

            employeeAnnouncmentMessage.setText("Please Fill All the Fields to Insert Employee Successfully...");
            return;
        }
        employeeAnnouncmentMessage.setText("");
        int selectedRowIndex = employeeTable.getSelectedRow();

        String primaryKeyValueAsString = employeeTable.getValueAt(selectedRowIndex, 0).toString();

        if (selectedRowIndex == -1) {
            if (employeeTable.getRowCount() == 0) {
                employeeAnnouncmentMessage.setText("Table is Empty...");
            } else {
                employeeAnnouncmentMessage.setText("Please click on a row to Update Employee");
            }
        } else {

            Employee employee = new Employee();
            EmployeeDatabaseOperations employeeDatabaseOperations = new EmployeeDatabaseOperations();
            employee.setId(Long.valueOf(employeeIdArea.getText()));
            employee.setFirstname(employeeFirstnameArea.getText());
            employee.setSurname(employeeSurnameArea.getText());
            employee.setPosition(employeePositionArea.getText());
            boolean isSuccess = employeeDatabaseOperations.updateEmployee(employee, primaryKeyValueAsString);
            if (isSuccess) {
                tableModel.setRowCount(0);
                displayEmployees();
                employeeAnnouncmentMessage.setText("Employee Successfully Updated...");
                employeeIdArea.setText("");
                employeeFirstnameArea.setText("");
                employeeSurnameArea.setText("");
                employeePositionArea.setText("");

                return;
            }
            employeeAnnouncmentMessage.setText("Employee Update Attempt Failed...");
            employeeIdArea.setText("");
            employeeFirstnameArea.setText("");
            employeeSurnameArea.setText("");
            employeePositionArea.setText("");

        }
    }//GEN-LAST:event_employeeUpdateButtonActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        try {
            String primaryKeyValueAsString = employeeTable.getValueAt(employeeTable.getSelectedRow(), 0).toString();
            
            EmployeeDatabaseOperations employeeDatabaseOperationsTemp = new EmployeeDatabaseOperations();
            Employee employee = employeeDatabaseOperationsTemp.getAnSpesificEmployeeDatas(primaryKeyValueAsString);
            employeeIdArea.setText(employee.getId().toString());
            employeeFirstnameArea.setText(employee.getFirstname());
            employeeSurnameArea.setText(employee.getSurname());
            employeePositionArea.setText(employee.getPosition());
        } catch (Exception ex) {
            employeeAnnouncmentMessage.setText(ex.toString());
        }


    }//GEN-LAST:event_employeeTableMouseClicked
    public boolean isEmployeeNumeric(String str) {
        try {
            Long.valueOf(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public boolean isEmployeePositiveInteger(String str) {
        try {
            int intValue = Integer.parseInt(str);
            return intValue > 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public boolean isEmployeeValidString(String str) {
        return str != null && !str.isEmpty();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel employeeAnnouncmentMessage;
    private javax.swing.JButton employeeDeleteButton;
    private javax.swing.JTextField employeeFirstnameArea;
    private javax.swing.JLabel employeeFirstnameLabel;
    private javax.swing.JTextField employeeIdArea;
    private javax.swing.JLabel employeeIdLabel;
    private javax.swing.JButton employeeInsertButton;
    private javax.swing.JTextField employeePositionArea;
    private javax.swing.JLabel employeePositionLabel;
    private javax.swing.JButton employeeSignOut;
    private javax.swing.JTextField employeeSurnameArea;
    private javax.swing.JLabel employeeSurnameLabel;
    private javax.swing.JTable employeeTable;
    private javax.swing.JButton employeeToProductButton;
    private javax.swing.JButton employeeUpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
