package companymanagementsystem.page;

import companymanagementsystem.entity.Product;
import companymanagementsystem.connections.ProductDatabaseOperations;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXCALIBUR
 */
public class ProductPage extends javax.swing.JFrame {

    private final DefaultTableModel tableModel;

    /**
     * Creates new form ProductPage
     */
    public ProductPage() {
        initComponents();
        setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) productTable.getModel();
        displayProducts();
    }

    private void displayProducts() {
        ProductDatabaseOperations productDatabaseOperations = new ProductDatabaseOperations();
        List<Product> products = productDatabaseOperations.getAllProducts();

        for (Product prod : products) {
            Object[] rowData = {
                prod.getCatalogNumber(),
                prod.getCategory(),
                prod.getPrice(),
                prod.getQuantity()
            };
            tableModel.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        catalog_numberArea = new javax.swing.JTextField();
        categoryArea = new javax.swing.JTextField();
        priceArea = new javax.swing.JTextField();
        quantityArea = new javax.swing.JTextField();
        productInsertButton = new javax.swing.JButton();
        productUpdateButton = new javax.swing.JButton();
        productsDeleteButton = new javax.swing.JButton();
        productToEmployeeButton = new javax.swing.JButton();
        productSignoutButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        productAnnouncementMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel5.setBackground(new java.awt.Color(215, 185, 61));

        jLabel16.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("</PRODUCT PAGE >");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("catalog_number :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("category");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("price");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("quantity");

        categoryArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryAreaActionPerformed(evt);
            }
        });

        quantityArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityAreaActionPerformed(evt);
            }
        });

        productInsertButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productInsertButton.setForeground(new java.awt.Color(255, 153, 0));
        productInsertButton.setText("INSERT");
        productInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productInsertButtonActionPerformed(evt);
            }
        });

        productUpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productUpdateButton.setForeground(new java.awt.Color(255, 153, 0));
        productUpdateButton.setText("UPDATE");
        productUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productUpdateButtonActionPerformed(evt);
            }
        });

        productsDeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productsDeleteButton.setForeground(new java.awt.Color(255, 153, 0));
        productsDeleteButton.setText("DELETE");
        productsDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsDeleteButtonActionPerformed(evt);
            }
        });

        productToEmployeeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productToEmployeeButton.setForeground(new java.awt.Color(255, 153, 0));
        productToEmployeeButton.setText("EMPLOYEE");
        productToEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productToEmployeeButtonActionPerformed(evt);
            }
        });

        productSignoutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productSignoutButton.setForeground(new java.awt.Color(255, 153, 0));
        productSignoutButton.setText("SIGN OUT");
        productSignoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSignoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productToEmployeeButton)
                .addGap(18, 18, 18)
                .addComponent(productSignoutButton)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(catalog_numberArea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productInsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoryArea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceArea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(quantityArea, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(productsDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(65, 65, 65))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productToEmployeeButton)
                    .addComponent(jLabel16)
                    .addComponent(productSignoutButton))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(catalog_numberArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(productInsertButton)))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(categoryArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(productUpdateButton)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(quantityArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(productsDeleteButton)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel6.setLayout(new javax.swing.OverlayLayout(jPanel6));

        jPanel7.setBackground(new java.awt.Color(215, 215, 84));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "catalog_number", "category", "price (?)", "quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.setGridColor(new java.awt.Color(255, 255, 51));
        productTable.getTableHeader().setReorderingAllowed(false);
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productTable);

        productAnnouncementMessage.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        productAnnouncementMessage.setForeground(new java.awt.Color(234, 117, 0));
        productAnnouncementMessage.setText("Announcement");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productAnnouncementMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(productAnnouncementMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantityAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityAreaActionPerformed

    private void productsDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsDeleteButtonActionPerformed
        productAnnouncementMessage.setText("");
        int selectedRowIndex = productTable.getSelectedRow();

        Object primaryKeyValue = productTable.getValueAt(selectedRowIndex, 0);
        String primaryKeyValueAsString = primaryKeyValue.toString();
        if (selectedRowIndex == -1) {
            if (productTable.getRowCount() == 0) {
                productAnnouncementMessage.setText("Table is Empty...");
            } else {
                productAnnouncementMessage.setText("Please click on a row to Delete a Product from Table");
            }
        } else {
            //Product product = new Product();
            ProductDatabaseOperations productDatabaseOperations = new ProductDatabaseOperations();

            boolean success = productDatabaseOperations.deleteProduct(primaryKeyValueAsString);
            if (success) {
                tableModel.setRowCount(0);
                displayProducts();
                productAnnouncementMessage.setText("Product Successfully Deleted...");
            } else {
                productAnnouncementMessage.setText("Product Delete Attempt Failed...");
            }

        }
    }//GEN-LAST:event_productsDeleteButtonActionPerformed

    private void categoryAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryAreaActionPerformed

    private void productInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productInsertButtonActionPerformed
        String price = priceArea.getText();

        if (!isNumeric(price)) {
            productAnnouncementMessage.setText("Please provide the type of the price correctly, as a Long");
            return;
        }
        String quantity = quantityArea.getText();
        if (!isPositiveInteger(quantity)) {
            productAnnouncementMessage.setText("Please provide the type of the price correctly, as a Long");
            return;
        }
        String catalog_number = catalog_numberArea.getText();
        if (!isValidString(catalog_number)) {
            productAnnouncementMessage.setText("Please provide the type of the catalog number correctly as a String");
            return;
        }
        String category = categoryArea.getText();
        if (!isValidString(category)) {
            productAnnouncementMessage.setText("Please provide the type of the category correctly, as a String");
            return;
        }

        Product product = new Product();
        product.setCatalogNumber(Long.valueOf(catalog_number));
        product.setCategory(category);
        product.setPrice(Long.valueOf(price));
        product.setQuantity(Long.valueOf(quantity));
        ProductDatabaseOperations productDatabaseOperations = new ProductDatabaseOperations();
        boolean success = productDatabaseOperations.insertProduct(product);

        if (success) {
            tableModel.setRowCount(0);
            displayProducts();
            catalog_numberArea.setText("");
            categoryArea.setText("");
            priceArea.setText("");
            quantityArea.setText("");

            productAnnouncementMessage.setText("Product Inserted Succesfully...");
        } else {
            productAnnouncementMessage.setText("Failed to Insert Product, Try Again...");
        }
    }//GEN-LAST:event_productInsertButtonActionPerformed

    private void productUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productUpdateButtonActionPerformed

        String price = priceArea.getText();

        /* if (!isNumeric(price)) {
            productAnnouncementMessage.setText("Please provide the type of the price correctly, as a Long");
            return;
        }
        String quantity = quantityArea.getText();
        if (!isPositiveInteger(quantity)) {
            productAnnouncementMessage.setText("Please provide the type of the price correctly, as a Long");
            return;
        }
        String catalog_number = catalog_numberArea.getText();
        if (!isValidString(catalog_number)) {
            productAnnouncementMessage.setText("Please provide the type of the catalog number correctly as a String");
            return;
        }
        String category = categoryArea.getText();
        if (!isValidString(category)) {
            productAnnouncementMessage.setText("Please provide the type of the category correctly, as a String");
            return;
        }*/

        productAnnouncementMessage.setText("");
        int selectedRowIndex = productTable.getSelectedRow();
        String primaryKeyValueAsString = productTable.getValueAt(selectedRowIndex, 0).toString();
        if (selectedRowIndex == -1) {
            if (productTable.getRowCount() == 0) {
                productAnnouncementMessage.setText("Table is Empty...");
            } else {
                productAnnouncementMessage.setText("Please click on a row to Update a Product");
            }
        } else {

            Product product = new Product();
            product.setCatalogNumber(Long.valueOf(catalog_numberArea.getText()));
            product.setCategory(categoryArea.getText());
            product.setPrice(Long.valueOf(priceArea.getText()));
            product.setQuantity(Long.valueOf(quantityArea.getText()));
            ProductDatabaseOperations productDatabaseOperations = new ProductDatabaseOperations();
            boolean success = productDatabaseOperations.updateProduct(product, primaryKeyValueAsString);
            if (success) {
                tableModel.setRowCount(0);
                displayProducts();
                productAnnouncementMessage.setText("Product Successfully Updated...");
            } else {
                productAnnouncementMessage.setText("Product Update Attempt Failed...");
            }

            catalog_numberArea.setText("");
            categoryArea.setText("");
            priceArea.setText("");
            quantityArea.setText("");

        }
    }//GEN-LAST:event_productUpdateButtonActionPerformed

    private void productToEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productToEmployeeButtonActionPerformed
        setVisible(false);
        EmployeePage employeePage = new EmployeePage();
        employeePage.setVisible(true);
    }//GEN-LAST:event_productToEmployeeButtonActionPerformed

    private void productSignoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSignoutButtonActionPerformed
        setVisible(false);
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
    }//GEN-LAST:event_productSignoutButtonActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked

        try {
            String primaryKeyValueAsString = productTable.getValueAt(productTable.getSelectedRow(), 0).toString();
            ProductDatabaseOperations productDatabaseOperationsTemp = new ProductDatabaseOperations();
            Product product = productDatabaseOperationsTemp.getAnSpesificProductDatas(primaryKeyValueAsString);
            catalog_numberArea.setText(product.getCatalogNumber().toString());
            categoryArea.setText(product.getCategory());
            priceArea.setText(product.getPrice().toString());
            quantityArea.setText(product.getQuantity().toString());

        } catch (Exception ex) {
            Logger.getLogger(ProductPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_productTableMouseClicked
    public static boolean isNumeric(String strNum) {
    if (strNum == null) {
        return false;
    }
    try {
        long d = Long.parseLong(strNum);
    } catch (NumberFormatException nfe) {
        return false;
    }
    return true;
}

    private boolean isPositiveInteger(String str) {
        try {
            int num = Integer.parseInt(str);
            return num > 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private boolean isValidString(String str) {
        return str.matches("[a-zA-Z0-9_]+"); // Metin alanlarý sadece harf, rakam ve alt çizgi içerebilir.
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField catalog_numberArea;
    private javax.swing.JTextField categoryArea;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceArea;
    private javax.swing.JLabel productAnnouncementMessage;
    private javax.swing.JButton productInsertButton;
    private javax.swing.JButton productSignoutButton;
    private javax.swing.JTable productTable;
    private javax.swing.JButton productToEmployeeButton;
    private javax.swing.JButton productUpdateButton;
    private javax.swing.JButton productsDeleteButton;
    private javax.swing.JTextField quantityArea;
    // End of variables declaration//GEN-END:variables
}
